"""add_campos_cartera_to_polizas

Revision ID: d15e0db15bee
Revises: 
Create Date: 2026-05-19 21:40:37.610271
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# Identificadores de revisión usados por Alembic
revision: str = 'd15e0db15bee'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Aplica los cambios al esquema de la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('polizas', sa.Column('centro_costo_solicitante', sa.String(length=100), nullable=True, comment='ID/Código del proyecto que solicitó la póliza'))
    op.add_column('polizas', sa.Column('centro_costo_pagador', sa.String(length=100), nullable=True, comment='ID/Código del fondo IDEXUD de donde salió la plata'))
    op.add_column('polizas', sa.Column('estado_cartera', sa.Enum('PENDIENTE_REINTEGRO', 'ABONADO', 'PAGADO', 'NO_APLICA', name='estadocarteraenum'), nullable=True, comment='Estado de la deuda con IDEXUD'))
    op.add_column('polizas', sa.Column('orden_pago_numero', sa.String(length=50), nullable=True, comment='Número de la OP'))
    op.add_column('polizas', sa.Column('orden_pago_fecha', sa.Date(), nullable=True, comment='Fecha de la Orden de Pago'))
    op.add_column('polizas', sa.Column('enlace_soporte_pago', sa.String(length=500), nullable=True, comment='Link de Nextcloud con la documentación financiera'))
    op.alter_column('polizas', 'numero_poliza',
               existing_type=sa.VARCHAR(length=100),
               nullable=False,
               existing_comment='Número de póliza emitido por la aseguradora')
    op.alter_column('polizas', 'vigencia_desde',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('polizas', 'vigencia_hasta',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('polizas', 'aseguradora_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('polizas', 'contratista_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revierte los cambios al esquema de la base de datos."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('polizas', 'contratista_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('polizas', 'aseguradora_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('polizas', 'vigencia_hasta',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('polizas', 'vigencia_desde',
               existing_type=sa.DATE(),
               nullable=True)
    op.alter_column('polizas', 'numero_poliza',
               existing_type=sa.VARCHAR(length=100),
               nullable=True,
               existing_comment='Número de póliza emitido por la aseguradora')
    op.drop_column('polizas', 'enlace_soporte_pago')
    op.drop_column('polizas', 'orden_pago_fecha')
    op.drop_column('polizas', 'orden_pago_numero')
    op.drop_column('polizas', 'estado_cartera')
    op.drop_column('polizas', 'centro_costo_pagador')
    op.drop_column('polizas', 'centro_costo_solicitante')
    # ### end Alembic commands ###
